# Generated by Django 4.2.2 on 2023-08-06 10:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_metalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalrequest',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 6)),
        ),
        migrations.AddField(
            model_name='metalrequest',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 6)),
        ),
    ]
