# Generated by Django 4.2.2 on 2023-08-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_plasticrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=120)),
                ('lname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('kg', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
